# Generated by Django 3.2.8 on 2021-10-28 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=255)),
                ('birthday', models.DateTimeField(default=datetime.datetime(2021, 10, 28, 17, 54, 38, 562605))),
                ('sex', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], default=1)),
                ('homeland', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
