# Generated by Django 3.2.8 on 2021-10-28 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 17, 56, 36, 824914)),
        ),
    ]
