# Generated by Django 3.2.8 on 2021-10-28 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0002_alter_artist_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='RealName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default=7.2178571428571425, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 10, 28)),
        ),
    ]
