# Generated by Django 3.2.8 on 2021-11-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0004_alter_artist_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birthday',
            field=models.DateField(default='2021-11-11'),
        ),
    ]
