# Generated by Django 3.2.8 on 2021-10-28 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_customeruser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 17, 56, 36, 809291)),
        ),
    ]
