# Generated by Django 3.2.8 on 2021-10-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_customeruser_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='birthday',
        ),
    ]
