# Generated by Django 3.2.8 on 2021-10-28 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_customeruser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 10, 28)),
        ),
    ]
