# Generated by Django 3.2.8 on 2021-11-07 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_customeruser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 11, 7)),
        ),
    ]
