# Generated by Django 3.2.8 on 2021-11-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_customeruser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='birthday',
            field=models.DateField(),
        ),
    ]
