# Generated by Django 3.2.8 on 2021-10-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0002_rename_auhtor_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
