# Generated by Django 3.2.8 on 2021-11-07 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Video', '0003_video_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='User_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.customeruser'),
            preserve_default=False,
        ),
    ]
